"""add_auth_audio_billing_fields

Revision ID: 835ef7968be8
Revises: f3eff45bcb2c
Create Date: 2026-05-03 10:25:36.174552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '835ef7968be8'
down_revision: Union[str, None] = 'f3eff45bcb2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('title', sa.String(length=500), nullable=True))
    op.add_column('meetings', sa.Column('audio_file_path', sa.String(length=1024), nullable=True))
    op.add_column('meetings', sa.Column('transcription_status', sa.String(length=50), nullable=True))
    op.alter_column('meetings', 'transcript_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('meetings', 'transcript_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('meetings', 'summary_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('meetings', 'action_items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.add_column('users', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('plan', sa.String(length=50), server_default='free', nullable=False))
    op.add_column('users', sa.Column('plan_expires_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.drop_column('users', 'plan_expires_at')
    op.drop_column('users', 'plan')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'display_name')
    op.execute("UPDATE meetings SET transcript_text = '' WHERE transcript_text IS NULL")
    op.execute("UPDATE meetings SET transcript_hash = '' WHERE transcript_hash IS NULL")
    op.execute("UPDATE meetings SET summary_text = '' WHERE summary_text IS NULL")
    op.execute("UPDATE meetings SET action_items = '[]'::jsonb WHERE action_items IS NULL")
    op.alter_column('meetings', 'action_items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('meetings', 'summary_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('meetings', 'transcript_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('meetings', 'transcript_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('meetings', 'transcription_status')
    op.drop_column('meetings', 'audio_file_path')
    op.drop_column('meetings', 'title')
    # ### end Alembic commands ###
